### ISSUE TITLE
formica new --deploy

### ISSUE THREAD

**Issue by muja** [flomotlik/formica#88]
Add `--deploy` flag to `formica new` which deploys the created stack automatically on successful creation.

Thoughts?

**Comment by flomotlik** [comment]
As with the other command I really want every action you take in Formica to be specific. I thought about this flag in the past (especially on new its less of a problem than on change because you're creating things) but I still prefer it to be specific. If you want to automate that you can of course simply do `formica new -c configfile.yaml && formica deploy -c configfile.yaml` in case that happens often.

Thanks for the feedback though, really appreciate it!
